import Head from "next/head";
import Example from "../components/LandingPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nexo - A CRM Software</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Example />
    </div>
  );
}
